server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      enabled: true
      server:
        mvc:
          path: /
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service   
          predicates:
            - Path=/payments/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurants/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/deliveries/**
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/ratings/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost